export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS= 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS= 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_VERIFICATION_REQUEST = 'USER_VERIFICATION_REQUEST';
export const USER_VERIFICATION_STATUS= 'USER_VERIFICATION_STATUS';
export const USER_VERIFICATION_FAIL = 'USER_VERIFICATION_FAIL';

export const USER_PENDING_REQUEST = 'USER_PENDING_REQUEST';
export const USER_PENDING_SUCCESS= 'USER_PENDING_SUCCESS';
export const USER_PENDING_FAIL = 'USER_PENDING_FAIL';



export const TUTOR_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const TUTOR_DETAILS_SUCCESS= 'USER_DETAILS_SUCCESS';
export const TUTOR_DETAILS_FAIL = 'USER_DETAILS_FAIL';

export const REVERIFICATION_DETAILS_REQUEST = 'REVERIFICATION_DETAILS_REQUEST';
export const REVERIFICATION_DETAILS_SUCCESS= 'REVERIFICATION_DETAILS_SUCCESS';
export const REVERIFICATION_DETAILS_FAIL = 'REVERIFICATION_DETAILS_FAIL';